### ISSUE TITLE
.net implementation ？

### ISSUE THREAD

**Issue by yanzixiang** [kanaka/websockify#211]
do u have any plans to create a .net implementation ?
on github, there r a lot of websocket libs that r ready for use,
such as
https://github.com/statianzo/Fleck
https://github.com/kerryjiang/SuperWebSocket

**Comment by DirectXMan12** [comment]
There are no plans immediately.  I noticed you also opened kanaka/noVNC#552.  Did you have any luck with https://github.com/lifeemotions/websocketproxy ?

**Comment by yanzixiang** [comment]
I think i missunderstood the porpurse of https://github.com/lifeemotions/websocketproxy,
I should use https://github.com/rickparrish/FleckProxy,
I have succeed in getting an websocket endpoint,
but when i tried to use noVNC to connect to the VNC server(REALVNC SERVER),
I get an error(1006),
i think maybe i should ask,
which VNC server is tested on WINDOWS using noVNC ?
https://github.com/kanaka/noVNC/issues/553

**Comment by samhed** [comment]
> which VNC server is tested on WINDOWS using noVNC ?

none, as far as I know :P

Everyone in the noVNC/Websockify team uses Linux

**Comment by kanaka** [comment]
There are several VNC servers that work fine on Windows. The problem is that websockify uses some modules that don't have great support in Windows. I do know that in the past there has been some success getting websockify to run on Windows using python 3.3 or higher. However, I would probably recommend the Node.js proxy on Windows since I think people have had more success with that on Windows. Or just run websockify on Linux to connect to your VNC server on Windows :-)

**Comment by totaam** [comment]
FWIW: I got websockify to run on python 2.7 on windows, took a bit of work and it's not pretty:
* the signal.SIGCHLD code is pretty straightforward
* handling WSAEWOULDBLOCK is not..
I will try to submit what I have.
